name: "52-gh-pages-main-deploy-docs"
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

# Needed for JamesIves/github-pages-deploy-action@v4
permissions:
  contents: write
  pages: write

jobs: 
  build-site:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v2

    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: npm ci
      working-directory: frontend

    - name: Build Storybook
      working-directory: frontend
      run: | # Install npm packages and build the Storybook files
        npx build-storybook --docs

    - name: list files for debugging before copying
      run: |
        pwd
        ls -lRta

    - name: compose web site
      run: |
        mkdir site
        cp -r frontend/docs-index/* site
        mkdir site/storybook
        cp -r frontend/storybook-static/* site/storybook

    - name: list files for debugging after copying
      run: |
        pwd
        ls -lRta

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site # The folder the action should deploy.
        branch: gh-pages


  enable-gh-pages:
    name: Enable GitHub Pages
    runs-on: ubuntu-latest
    needs: build-site

    steps:
    - name: Enable GitHub Pages on gh-pages branch
      run: |
        echo '{"source":{"branch":"gh-pages","path":"/"}}' > enable-gh-pages.json
        gh api /repos/${{github.repository}}/pages -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          --input enable-gh-pages.json
    - name: Set link to GitHub Pages on home page 
      run: |
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}"
          gh repo edit ${OWNER_PLUS_REPOSITORY} --homepage ${HOMEPAGE}
          

     